source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'bootsnap', require: false
gem 'btree'
gem 'csv'
gem 'puma'
gem 'railties'

group :development, :test do
  gem 'pry'
end
